#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

AppBundle_contact:
    pattern:  /contact
    defaults: { _controller: AppBundle:Pages:contact }
    requirements:
        _method:  GET|POST

AppBundle_blog_show:
    pattern:  /blog/{id}
    defaults: { _controller: AppBundle:Blogs:show }
    requirements:
        _method:  GET
        id: \d+

AppBundle_blog:
    pattern:  /blog
    defaults: { _controller: AppBundle:Pages:index }
    requirements:
        _method:  GET

AppBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: AppBundle:Comments:create }
    requirements:
        _method:  POST
        blog_id: \d+

AppBundle_homepage:
    pattern:  /
    defaults: { _controller: AppBundle:Default:index }
    requirements:
        _method: GET